"""Regenerate docs/TOOLS.md from the live FastMCP registration.

    python tools/dump_tool_index.py
"""

from __future__ import annotations

import asyncio
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from m365_mcp.server import FAMILIES, mcp  # noqa: E402


def first_line(text: str | None) -> str:
    for line in (text or "").strip().splitlines():
        if line.strip():
            return line.strip()
    return ""


def main() -> None:
    tools = asyncio.run(mcp.list_tools())
    by_name = {t.name: t for t in tools}
    out = [
        "# Tool index",
        "",
        "Generated by `tools/dump_tool_index.py` - do not edit by hand.",
        "",
        "%d tools." % len(tools),
        "",
    ]
    placed: set[str] = set()
    for prefix, description in FAMILIES.items():
        names = sorted(n for n in by_name if n.startswith(prefix))
        if not names:
            continue
        out.append("## `%s*` - %s" % (prefix, description))
        out.append("")
        out.append("| tool | what it does |")
        out.append("| --- | --- |")
        for name in names:
            placed.add(name)
            out.append("| `%s` | %s |" % (name, first_line(by_name[name].description)))
        out.append("")
    rest = sorted(set(by_name) - placed)
    if rest:
        out.append("## other")
        out.append("")
        out.append("| tool | what it does |")
        out.append("| --- | --- |")
        for name in rest:
            out.append("| `%s` | %s |" % (name, first_line(by_name[name].description)))
        out.append("")
    path = os.path.join(ROOT, "docs", "TOOLS.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print("wrote %s (%d tools)" % (path, len(tools)))


if __name__ == "__main__":
    main()
